---
hero_image: images/compass-maze.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Kompasdoolhof
description: Gebruik de Sense HAT als kompas en navigeer uit een doolhof.
original_url: https://codeclubprojects.org/en-GB/sense-hat/compass-maze
interests: games
technologies: sense-hat
site_areas: projects
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'Inleiding'
  - 
    title: De kompasrichting vinden
  - 
    title: Laat de kompasrichting zien
  - 
    title: Navigeren door het doolhof
  - 
    title: Voeg kleuren toe
  - 
    title: 'Uitdaging: beloon de speler'
  - 
    title: 'Uitdaging: maak je eigen doolhof'
