---
hero_image: images/compass-maze.png
theme: नीला
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Compass Maze (कंपास भूलभुलैया)
description: Sense HAT का उपयोग एक कंपास के रूप में करें और भूलभुलैया से बाहर नेविगेट करें।
original_url: https://codeclubprojects.org/en-GB/sense-hat/compass-maze
interests: games
technologies: sense-hat
site_areas: प्रोजेक्ट
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'Introduction'
  - 
    title: कंपास की दिशा ढूँढना
  - 
    title: कंपास की दिशा दिखाना
  - 
    title: भूलभुलैया में नेविगेट करना
  - 
    title: रंग जोड़ना
  - 
    title: 'चुनौती: खिलाड़ी को पुरस्कृत करना'
  - 
    title: 'चुनौती: अपनी खुद की भूलभुलैया बनाना'
