---
hero_image: images/compass-maze.png
theme: नीला
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: कंपास भूलभुलैया
description: Sense HAT का उपयोग एक कंपास के रूप में करें और भूलभुलैया से बाहर नेविगेट करें।
original_url: https://codeclubprojects.org/en-GB/sense-hat/compass-maze
interests: गेम
technologies: sense-hat
site_areas: प्रोजेक्ट
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'Introduction: '
  - 
    title: Finding the compass direction
  - 
    title: Showing the compass direction
  - 
    title: Navigating the maze
  - 
    title: Add colours
  - 
    title: 'Challenge: Reward the player'
  - 
    title: 'Challenge: Create your own maze'
