---
hero_image: images/compass-maze.png
theme: albastru
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Compasul labirintului
description: Folosiți Sense HAT ca o busolă și navigați dintr-un labirint.
original_url: https://codeclubprojects.org/en-GB/sense-hat/compass-maze
interests: jocuri
technologies: sens pălărie
site_areas: proiecte
hardware: sens pălărie
software: ''
version: 3
last_tested: 01-01-2017
steps:
  - 
    title: 'Introduction'
  - 
    title: Găsirea direcției busolei
  - 
    title: Se afișează direcția busolă
  - 
    title: Navigarea în labirint
  - 
    title: Adăugați culori
  - 
    title: 'Provocare: recompensa jucătorul'
  - 
    title: 'Provocare: creați propriul labirint'
