---
hero_image: images / compass-maze.png
theme: kék
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Compass Maze
description: Use the Sense HAT as a compass and navigate out of a maze.
original_url: https://codeclubprojects.org/en-GB/sense-hat/compass-maze
interests: games
technologies: sense-hat
site_areas: projects
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'Introduction'
  - 
    title: Finding the compass direction
  - 
    title: Showing the compass direction
  - 
    title: Navigating the maze
  - 
    title: Add colours
  - 
    title: 'Challenge: Reward the player'
  - 
    title: 'Challenge: Create your own maze'
