---
hero_image: images/compass-maze.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Laberinto con Brújula
description: Usa el Sense HAT como brújula y navega fuera de un laberinto.
original_url: https://codeclubprojects.org/en-GB/sense-hat/compass-maze
interests: games
technologies: sense-hat
site_areas: projects
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: Introducción
  completion: engaged
- title: Encontrando la dirección de la brújula
- title: Mostrando la dirección de la brújula
- title: Navegando por el laberinto
- title: Agregar colores
- title: 'Desafío: recompensa al jugador'
  completion: internal
- title: 'Desafío: crea tu propio laberinto'
