---
hero_image: images/compass-maze.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Une boussole dans le labyrinthe
description: Utilise le Sense HAT comme boussole et sors d'un labyrinthe.
original_url: https://codeclubprojects.org/en-GB/sense-hat/compass-maze
interests: games
technologies: sense-hat
site_areas: projects
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - title: Introduction
  - title: Trouver la direction de la boussole
  - title: Montrer la direction de la boussole
  - title: Naviguer dans le labyrinthe
  - title: Ajouter des couleurs
  - title: 'Défi : récompense le joueur'
  - title: 'Défi : Crée ton propre labyrinthe'
